// routes/teamCommission.js

const express = require('express');
const router = express.Router();

/**
 * Distributes hourly team commissions up to 3 levels with VIP level checks.
 * @param {Object} pool - MySQL database connection pool
 * @param {Number} earnerId - The ID of the user whose device generated the income
 * @param {Number} hourlyIncome - The total hourly income generated by the device
 */
async function distributeHourlyTeamCommissions(pool, earnerId, hourlyIncome) {
  const connection = await pool.getConnection();
  try {
    await connection.beginTransaction();

    // 1. Get the earner's VIP level and direct upline (Level 1)
    const [earnerRows] = await connection.query(
      `SELECT id, vip_level, referred_by FROM users WHERE id = ?`,
      [earnerId]
    );
    if (earnerRows.length === 0) {
      await connection.rollback();
      return;
    }
    const earner = earnerRows[0];
    const earnerVip = earner.vip_level || 0;

    // Define commission tiers
    const tiers = [
      { level: 1, rate: 0.050 }, // 5%
      { level: 2, rate: 0.022 }, // 2.2%
      { level: 3, rate: 0.011 }  // 1.1%
    ];

    let currentUserId = earner.referred_by;

    // 2. Loop through up to 3 levels up
    for (let i = 0; i < tiers.length; i++) {
      if (!currentUserId) break; // No more uplines

      // Fetch current upline details
      const [uplineRows] = await connection.query(
        `SELECT id, vip_level, referred_by, balance FROM users WHERE id = ?`,
        [currentUserId]
      );

      if (uplineRows.length === 0) break;
      const upline = uplineRows[0];
      const uplineVip = upline.vip_level || 0;

      // RULE CHECK: Upline VIP level must be >= Downline (Earner) VIP level
      if (uplineVip >= earnerVip) {
        const tier = tiers[i];
        const commissionAmount = hourlyIncome * tier.rate;

        if (commissionAmount > 0) {
          // Update upline balance
          await connection.query(
            `UPDATE users SET balance = balance + ? WHERE id = ?`,
            [commissionAmount, upline.id]
          );

          // Optional: Log this commission to a team_rewards table for history tracking
          await connection.query(
            `INSERT INTO team_commissions (user_id, from_user_id, level, amount, created_at) 
             VALUES (?, ?, ?, ?, NOW())`,
            [upline.id, earnerId, tier.level, commissionAmount]
          );
        }
      }

      // Move up to the next level (upline's upline)
      currentUserId = upline.referred_by;
    }

    await connection.commit();
  } catch (error) {
    await connection.rollback();
    console.error("Error distributing hourly team commissions:", error);
  } finally {
    connection.release();
  }
}

// Example route placeholder (you can add your specific router endpoints here if needed)
router.get('/', (req, res) => {
  res.json({ message: "Team commission route active" });
});

module.exports = router;